[package]
name = "even_fib_sum"
version = "0.1.0"
authors = ["nobel khandaker <nobel@huskers.unl.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
